apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-server
  labels:
    app: judge0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0
  template:
    metadata:
      labels:
        app: judge0
    spec:
      containers:
        - name: judge0-server
          image: {{ .Values.image.judge0 }}
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: submissions
              mountPath: /box
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
          env:
            - name: POSTGRES_HOST
              value: "postgres.default.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "Mellob198978SadcDWFewd"
            - name: POSTGRES_DB
              value: "judge0"
            - name: REDIS_HOST
              value: "10.224.0.15"
            - name: REDIS_PASSWORD
              value: "redispassword"
        - name: judge0-worker
          image: {{ .Values.image.judge0 }}
          command: ["./scripts/workers"]
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: submissions
              mountPath: /box
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
          env:
            - name: POSTGRES_HOST
              value: "postgres.default.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "Mellob198978SadcDWFewd"
            - name: POSTGRES_DB
              value: "judge0"
            - name: REDIS_HOST
              value: "10.224.0.15"
            - name: REDIS_PASSWORD
              value: "redispassword"
      volumes:
        - name: submissions
          emptyDir: {}
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup  # Mounts the host's cgroup directory
