apiVersion: v1
kind: Service
metadata:
  name: judge0-service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: judge0-server
